rungalileo/galileo-js

src/observe/callback.ts
Removes rounding for `time_to_first_token` now that the API switched to float.
=> fix(observe): Switch time_to_first_token to float

.github/workflows/update-api-types.yml, package-lock.json, package.json
This adds a workflow that gets the OpenAPI spec and generates the
Typescript types. The API spec that it fetches is a limited API with
only endpoints that are intended for use in the client.
=> build: Generate client API types

src/api-client.ts
There's currently an infinite loop due to a circular dependency: `apiKeyLogin` &rarr; `makeRequest` &rarr; `getToken` &rarr; `apiKeyLogin` &rarr; `makeRequest` &rarr; `getToken` etc.
This results in some call stack exceeded errors like this:
```
/app/node_modules/@rungalileo/galileo/dist/api-client.js:140
return response.data;
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/app/node_modules/@rungalileo/galileo/dist/api-client.js:79
return await this.makeRequest(RequestMethod.POST, routes_types_js_1.Routes.apiKeyLogin, {
^
RangeError: Maximum call stack size exceeded
```
This changes fixes this by not getting the token for the `/login/api_key` route
=> Don't require token for api key login route

examples/datasets/workflow.js, package-lock.json, package.json, src/api-client.ts, src/index.ts, src/types/routes.types.ts, src/utils/datasets.ts, tests/utils/datasets.test.ts
This function accepts datasets in the same format as in the Python
client, as well as an optional name.
=> feat(datasets): Add `createDataset` function

README_G20.md, src/api-client/base-client.ts, src/api-client/galileo-client.ts, src/api-client/services/experiment-service.ts, src/api-client/services/prompt-template-service.ts, src/api-client/services/trace-service.ts, src/index.ts, src/types/experiment.types.ts, src/types/prompt-template.types.ts, src/types/routes.types.ts, src/utils/experiments.ts, src/utils/galileo-logger.ts, src/utils/prompt-templates.ts, src/utils/scorers.ts
Adding the ability to run experiments using prompt templates:
```js
import { createPromptTemplate, runExperiment } from 'galileo-experimental';
const template = await createPromptTemplate({
template: [{ role: 'user', content: 'Say "Hello, {name}"!' }],
projectName: 'my-test-project-5',
name: `Hello name prompt`
});
// Run the experiment. You'll receive a URL to view the results.
await runExperiment({
name: `Test Experiment`,
datasetName: 'names',
promptTemplate: template,
metrics: ['output_tone'],
projectName: 'my-test-project-5'
});
```
=> G2.0 Prompt run experiments

package-lock.json, package.json, src/observe/callback.ts
Tiny update to the token usage counter to pull from `llmOutput.usage` or `llmOutput.estimatedTokenUsage` if `llmOutput.tokenUsage` is not available.
=> feat: Support alternative forms of token usage returned by LLM output

src/utils/datasets.ts, tests/utils/datasets.test.ts
This change makes it possible to create datasets by passing objects or strings:
```typescript
// rows data with object
await createDataset(
[
{input: {virtue: "benevolence", voice: "Oprah Winfrey"}},
{input: {virtue: "trustworthiness", voice: "Barack Obama"}},
],
"rows data with object"
);
// rows data with string
await createDataset(
[
{input: "salmon"},
{input: "cod"},
],
"rows data with string"
);
// columns data with object
await createDataset(
{
input: [
{virtue: "benevolence", voice: "Oprah Winfrey"},
{virtue: "trustworthiness", voice: "Barack Obama"},
],
},
"columns data with object"
);
// columns data with string
await createDataset(
{
input: [
"salmon",
"cod",
],
},
"columns data with string"
);
```
=> feat(core): JSONify dataset content if objects are supplied

src/api-client/base-client.ts, tests/utils/experiments.test.ts
https://app.shortcut.com/galileo/story/27088/using-an-invalid-api-key-in-the-typescript-client-produces-verbose-unclear-messages
=> Improve error handling for failing requests

src/openai.ts
This was causing dependency issues in a customer's NextJS application. Specifying a local type and removing the OpenAI client import that was causing the issue.
https://app.shortcut.com/galileo/story/27109/typescript-sdk-issues
=> fix: removing the OpenAI dependency from wrapOpenAI

package-lock.json, package.json, src/types/index.ts
Before:
```
import { Message, MessageRole } from "galileo/dist/types/message.types";
```
After:
```
import { Message, MessageRole } from "galileo/types";
```
https://app.shortcut.com/galileo/story/27311/typescript-sdk-it-should-be-easier-to-import-messagerole
=> feat: making it easier to import types using "galileo/types"

src/types/log.types.ts, tests/utils/galileo-logger.test.ts
**Ticket:**
- [sc-28067](https://app.shortcut.com/galileo/story/28067/typescript-sdk-llm-span-input-logs-entire-conversation-chat-history-at-every-step)
**Description:**
This pull request includes changes to ensure message history integrity of LLM spans. The most important changes involve modifying how input and output data are processed and adding a new test case to validate the integrity of message history when LLM spans are added.
**Tests:**
=> fix: Use structuredClone for LLM input/output in LlmSpan class

src/utils/galileo-logger.ts, tests/utils/galileo-logger.test.ts
https://app.shortcut.com/galileo/story/26366/g2-0-ts-sdk-add-a-way-to-turn-off-logging
Mirroring the functionality in the Python client library
=> feat: Turn off logging by setting the GALILEO_LOGGING_DISABLED env var

src/index.ts, src/singleton.ts
https://app.shortcut.com/galileo/story/28601/typescript-sdk-using-openai-wrapper-logs-every-llm-step-as-a-different-trace-unless-workflow-is-used
This will allow users to access singleton logger and start a trace that can be added to in wrapped calls:
```
import { wrapOpenAI, flush, init, getLogger, wrapOpenAI } from 'galileo';
import { OpenAI } from 'openai';
const openai = wrapOpenAI(
new OpenAI({ apiKey: process.env.OPENAI_API_KEY })
);
await init({
projectName: 'my-test-project-4',
logStreamName: 'my-test-log-stream'
});
// Get the singleton logger instance
const logger = await getLogger();
logger.startTrace(...);
const result1 = await openai.chat.completions.create({
model: 'gpt-4o',
messages: [{ content: 'Say hello world!', role: 'user' }]
});
const result2 = await …
```
=> feat: Adding a getLogger() method to access the singleton logger

examples/prompts/createprompt.js, package.json, src/utils/prompt-templates.ts
This PR solves https://app.shortcut.com/galileo/story/26800/g2-0-typescript-sdk-relax-the-input-type-constraint-on-messagerole
```
➜  galileo-js git:(relax-the-input-type-constraint) ✗ node examples/prompts/createprompt.js
{
name: 'Hello name prompt!',
id: '1656acc7-6c9f-4819-8484-36ef46641c57',
template: 'Hi Andrii!',
selected_version: {
template: 'Hi Andrii!',
version: 0,
id: 'd43ddfee-2f97-4a30-becd-1e8205aea242'
},
selected_version_id: 'd43ddfee-2f97-4a30-becd-1e8205aea242',
all_versions: [
{
template: 'Hi Andrii!',
version: 0,
id: 'd43ddfee-2f97-4a30-becd-1e8205aea242'
}
],
all_available_versions: [ 0 ],
total_versions: 1,
max_version: 0
}
```
=> fix: Relax the input type constraint on MessageRole

src/api-client/galileo-client.ts, src/api-client/services/trace-service.ts, src/singleton.ts, src/types/log.types.ts, src/types/routes.types.ts, src/types/step.types.ts, src/utils/galileo-logger.ts, tests/utils/galileo-logger.test.ts
Adding Session management to the GalileoLogger
```
await logger.startSession({
name: 'test session',
previousSessionId: '6c4e3f7e-4a9a-4e7e-8c1f-3a9a3a9a3a9d',
externalId: 'appSessionID123'
});
...
logger.clearSession();
```
https://app.shortcut.com/galileo/story/29395/sdk-add-session-compatibility-to-the-galileologger-ts
=> feat: adding Session management

.github/workflows/test.yaml
This PR resolves https://app.shortcut.com/galileo/story/29239/g2-0-typescript-sdk-enable-testing-multi-nodejs-version-on-ci
=> ci: Test on multiple nodeJS versions

examples/datasets/datasets.js, src/api-client/base-client.ts, src/api-client/galileo-client.ts, src/api-client/services/dataset-service.ts, src/index.ts, src/types/dataset.types.ts, src/utils/datasets.ts, tests/utils/datasets.test.ts
The existing function was not exported and had a few issues. This
modifies it to call the correct endpoint, pass the etag in the header,
and stringify JSON values.
=> feat: Add `addRowsToDataset` function

README.md, examples/logger/logger.js, src/types/log.types.ts, src/types/step.types.ts, tests/utils/galileo-logger.test.ts
Currently the TypeScript SDK is not sending durations or token counts to the API. This is because the JSON objects being created have the wrong structure, and are not typechecked against the OpenAPI spec.
This fix moves these metrics to the right JSON format, but going forward we should be creating strongly typed objects from the OpenAI spec to ensure that this can't happen.
This fixes:
[SC-30381](https://app.shortcut.com/galileo/story/30381/typescript-openai-wrapper-doesn-t-capture-system-metrics)
=> fix: Moving duration and tokens to metrics to make them work

.github/workflows/publish-docs.yaml, local-plugins/format-for-galileo.mjs
Our generated docs contain a link with a sha of the release branch. This means docs PRs contain lots of noise as these links change a lot.
E.g.: https://github.com/rungalileo/docs-official/pull/264/files#diff-98c677dba8aea178cf837bf252b5d44b9b625450f117991320149f57e6e7c829 - 117 files changed, most are just the SHA changing.
To simplify, these are now mapped to main. As the docs should be up to date with main, this should rarely lead to a broken link.
=> fix: Changing SHA to main in github links

package-lock.json, src/api-client/galileo-client.ts, src/api-client/services/scorer-service.ts, src/types/scorer.types.ts, src/utils/metrics.ts, src/utils/scorers.ts, tests/utils/scorers.test.ts
https://app.shortcut.com/galileo/story/35903/ts-sdk-add-output-type-to-createcustomllmmetric
=> feat(scorers): Add output type to createCustomLlmMetric

examples/datasets/datasets.js, src/api-client/galileo-client.ts, src/api-client/index.ts, src/api-client/services/dataset-service.ts, src/index.ts, src/types/routes.types.ts, src/utils/datasets.ts, tests/utils/datasets.test.ts
**Shortcut:**
- [sc-32753 - [Javascript SDK] Add MVP synthetic dataset functionality](https://app.shortcut.com/galileo/story/32753/javascript-sdk-add-mvp-synthetic-dataset-functionality)
**Description:**
This PR adds the extendDataset function to the Javascript SDK:
**Pending improvements:**
- Just get a model alias instead of PromptSettings.
- Adapt the interface for "source_dataset" example.
Extends a synthetic dataset based on the provided prompt and configuration.
- This function starts a background job to generate synthetic data and waits for its completion.
- Not scoped to any project.
**Parameters:**
| Name              | Type                                      | Description                                                  | …
=> feat: Implement extendDataset functionality

examples/metrics/metrics.js, examples/package-lock.json, src/api-client/galileo-client.ts, src/api-client/services/logstream-service.ts, src/index.ts, src/types/metrics.types.ts, src/utils/experiments.ts, src/utils/log-streams.ts, src/utils/metrics.ts, tests/utils/experiments.test.ts, tests/utils/metrics.test.ts
**Shortcut:**
- [sc-39363 / Allow users to turn on a metric in the logstream from the getting started code snippet](https://app.shortcut.com/galileo/story/39363/allow-users-to-turn-on-a-metric-in-the-logstream-from-the-getting-started-code-snippet)
- [sc-41457 / Enable metrics is missing for TypeScript](https://app.shortcut.com/galileo/story/41457/enable-metrics-is-missing-for-typescript)
**Description:**
This PR exposes the **enableMetrics** function to allow users to register metrics for log streams and experiments. The function supports built-in Galileo scorers, custom metrics with versions, and local metrics with custom scorer functions. 
The experiment metrics implementation was refactored to align with the Python SDK architecture using a unified **createMetricConfigs** utility. …
=> feat: Enable metrics for LogStream

src/utils/metrics.ts
_Fix regression error / No ticket_
**Description:**
Scorer retrieval by filtering with metric names in createMetricConfigs
=> fix: Scorer retrieval by filtering with metric names in createMetricConfigs
